// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcmslzzuxycztdlkprbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjbXNsenp1eHljenRkbGtwcmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3ODQyNDIsImV4cCI6MjA1NjM2MDI0Mn0.2eakhdROAcntgb7aJIYNrH8USgdJGlvw9ng0UE_zK6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});